"""Tool-surface metrics — the shared measurement core.

One definition of every number, imported by both the live survey (`mcp_survey.py`, run against
production) and the offline CI gate (`check_tool_surface.py`, run against the pinned baseline).
Keeping them in one module is deliberate: a gate that measures something subtly different from
what the survey reports is a gate nobody trusts.

Tokens are estimated as `len(json.dumps(x)) / 4`. That is a comparative heuristic, not a
tokenizer: treat absolute values as +/-20% and the ratios and rankings as sound. Every threshold
in the standards is set with that slack already allowed for.
"""

from __future__ import annotations

import json
from typing import Any

# The pinned, digest-attested snapshot of every backend's tool definitions. Generated by
# scripts/snapshot_fleet.py; the same artifact the README inventory and drift tripwire use.
BASELINE = "genefoundry_router/data/fleet-baseline.json"

# docs/TOOL-SURFACE-BUDGET-STANDARD-v1.md
MAX_TOOL_TOKENS = 1_200
MAX_SERVER_TOKENS = 10_000
MAX_ROUTER_TOKENS = 20_000

# docs/TOOL-SCHEMA-DOCUMENTATION-STANDARD-v1.md
MIN_DOCUMENTED_PCT = 100


def tokens(obj: Any) -> int:
    """Approximate token cost of a JSON-serialisable object (chars/4)."""
    return len(json.dumps(obj)) // 4


def properties(tool: dict[str, Any]) -> dict[str, dict[str, Any]]:
    """Every input property of a tool, by name."""
    schema = tool.get("inputSchema") or {}
    return dict(schema.get("properties") or {})


def declares_enum(prop: dict[str, Any]) -> bool:
    """True if a property constrains its value to a closed set.

    An enum may sit directly on the property, or inside an `anyOf` branch — which is how
    pydantic renders `Literal[...] | None`, the fleet's usual shape for an optional filter.
    """
    if prop.get("enum"):
        return True
    return any(
        isinstance(branch, dict) and branch.get("enum") for branch in prop.get("anyOf") or []
    )


def is_array(prop: dict[str, Any]) -> bool:
    """True if a property accepts a JSON array (directly or via an `anyOf` branch)."""
    if prop.get("type") == "array":
        return True
    return any(
        isinstance(branch, dict) and branch.get("type") == "array"
        for branch in prop.get("anyOf") or []
    )


def surface_metrics(tools: list[dict[str, Any]]) -> dict[str, Any]:
    """The full metric row for one server's advertised tool list."""
    total = tokens(tools)
    out = sum(tokens(t.get("outputSchema") or {}) for t in tools)
    props = [p for t in tools for p in properties(t).values()]
    documented = [p for p in props if p.get("description")]
    return {
        "tools": len(tools),
        "surface": total,
        "out_pct": round(100 * out / total) if total else 0,
        "params": len(props),
        "documented": len(documented),
        "doc_pct": round(100 * len(documented) / len(props)) if props else 100,
        "enums": sum(1 for p in props if declares_enum(p)),
        "examples": sum(1 for p in props if p.get("examples")),
    }
